name: test
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'dev'
      - 'master'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Go Version
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: test
        env:
          LD_LIBRARY_PATH: /home/runner/go/pkg/mod/github.com/tonkeeper/tongo@v1.0.16-0.20230528101916-42f3dc2194c8/lib/linux
          LITE_SERVERS: ${{ secrets.LITE_SERVERS }}
        run: |
          make test
